// Warning: generated file; your changes could be lost when a new file is generated.
#r @"System.dll"
#r @"System.Core.dll"
#r @"System.Numerics.dll"
#r @"..\..\packages\Aether\lib\net40\Aether.dll"
#r @"..\..\packages\Chiron\lib\net40\Chiron.dll"
#r @"..\..\packages\FParsec\lib\net40-client\FParsec.dll"
#r @"..\..\packages\FParsec\lib\net40-client\FParsecCS.dll"
#r @"..\..\packages\Chessie\lib\net40\Chessie.dll"
#r @"..\..\MAG.Events\bin\Debug\MAG.Events.dll"